[package]
authors = ["Robert Collins <robert.collins@cognite.com>"]
categories = ["api-bindings", "web-programming"]
default-run = "dump-features"
edition = "2018"
keywords = ["continualdeployment"]
license = "Apache-2.0"
name = "unleash-api-client"
publish = false
version = "0.1.0"
readme = "README.md"


[badges]
[badges.maintenance]
status = "experimental"

[dependencies]
anyhow = "*"
async-std = "1.5.0"
http-client = "2.0.0"
http-types = "1.2.0"
ipaddress = "0.1.2"
serde_json = "1.0.52"
surf = "2.0.0-alpha.2"

[dependencies.serde]
features = ["derive"]
version = "1.0"
