[package]
name = "unleash-api-client"
version = "0.1.0"
authors = ["Robert Collins <robert.collins@cognite.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
