[package]
authors = ["Robert Collins <robert.collins@cognite.com>"]
categories = ["api-bindings", "web-programming"]
default-run = "dump-features"
description = "An https://unleash.github.io/ API client"
edition = "2018"
homepage = "https://github.com/cognitedata/unleash-client-rust/"
keywords = ["continualdeployment"]
license = "Apache-2.0"
name = "unleash-api-client"
publish = false
readme = "README.md"
repository = "https://github.com/cognitedata/unleash-client-rust/"
version = "0.1.0"
[badges]
[badges.maintenance]
status = "experimental"

[dependencies]
anyhow = "*"
arc-swap = "0.4.6"
async-std = "1.5.0"
futures = "0.3.4"
futures-timer = "3.0.2"
hostname = "0.3.1"
http-client = "2.0.0"
http-types = "1.2.0"
ipaddress = "0.1.2"
log = "0.4.8"
maplit = "1.0.2"
murmur3 = "0.5.1"
rand = "0.7.3"
serde_json = "1.0.52"
surf = "2.0.0-alpha.2"

[dependencies.chrono]
features = ["serde"]
version = "0.4.11"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.tokio]
features = ["rt-threaded", "macros"] 
version = "0.2.20"

[dev-dependencies]
simple_logger = "1.6.0"

[features]
functional = []
